name: M5StickC Plus2 Only
on:
  workflow_dispatch:
  pull_request:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build Marauder Binaries
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install ESP32 Boards and Compile TestFile
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: TestFile.ino
          arduino-board-fqbn: esp32:esp32:esp32s2
          platform-url: https://github.com/espressif/arduino-esp32/releases/download/3.0.3/package_esp32_dev_index.json
          
      #- name: Show Arduino dir structure
      #  run: |
      #    find /home/runner/.arduino15/packages/esp32/hardware/
        
      #- name: Pull arduino-esp32 v2.0.4
      #  uses: actions/checkout@v2
      #  with:
      #    repository: espressif/arduino-esp32
      #    # ref: 2.0.4
      #    # path: 2.0.4arduino-esp32
          
      #- name: Pull arduino-esp32 v2.0.10
      #  uses: actions/checkout@v2
      #  with:
      #    repository: espressif/arduino-esp32
      #    ref: 3.0.3
      #    path: 3.0.3
          
      - name: Install AsyncTCP
        uses: actions/checkout@v2
        with:
          repository: me-no-dev/AsyncTCP
          ref: master
          path: CustomAsyncTCP
          
      - name: Install MicroNMEA
        uses: actions/checkout@v2
        with:
          repository: stevemarple/MicroNMEA
          ref: v2.0.6
          path: CustomMicroNMEA
          
      - name: Install ESPAsyncWebServer
        uses: actions/checkout@v2
        with:
          repository: bmorcelli/ESPAsyncWebServer
          ref: master
          path: CustomESPAsyncWebServer
          
      - name: Install TFT_eSPI
        uses: actions/checkout@v2
        with:
          repository: Bodmer/TFT_eSPI
          ref: V2.5.34
          path: CustomTFT_eSPI

      - name: Install lv_arduino
        uses: actions/checkout@v2
        with:
          repository: lvgl/lv_arduino
          ref: 3.0.0
          path: Customlv_arduino

      - name: Install JPEGDecoder
        uses: actions/checkout@v2
        with:
          repository: Bodmer/JPEGDecoder
          ref: 1.8.0
          path: CustomJPEGDecoder

      - name: Install NimBLE-Arduino
        uses: actions/checkout@v2
        with:
          repository: h2zero/NimBLE-Arduino
          ref: 1.4.2
          path: CustomNimBLE-Arduino

      - name: Install Adafruit_NeoPixel
        uses: actions/checkout@v2
        with:
          repository: adafruit/Adafruit_NeoPixel
          ref: 1.10.7
          path: CustomAdafruit_NeoPixel

      - name: Install ArduinoJson
        uses: actions/checkout@v2
        with:
          repository: bblanchon/ArduinoJson
          ref: v6.18.2
          path: CustomArduinoJson

      #- name: Install SwitchLib
      #  uses: actions/checkout@v2
      #  with:
      #    repository: justcallmekoko/SwitchLib
      #    ref: main
      #    path: CustomSwitchLib
          
      - name: Install LinkedList
        uses: actions/checkout@v2
        with:
          repository: ivanseidel/LinkedList
          ref: v1.3.3
          path: CustomLinkedList
          
      - name: Install EspSoftwareSerial
        uses: actions/checkout@v2
        with:
          repository: plerup/espsoftwareserial
          ref: 8.1.0
          path: CustomEspSoftwareSerial
          
      #- name: Search for SD lib in arduino-esp32 v2.0.4
      #  run: |
      #    find /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32 -name "SD"
          
      - name: Configure TFT_eSPI
        run: |
          rm -f CustomTFT_eSPI/User_Setup_Select.h
          ls
          cp /home/runner/work/ESP32Marauder/ESP32Marauder/User_Setup_Select.h CustomTFT_eSPI/
          cp /home/runner/work/ESP32Marauder/ESP32Marauder/User_Setup_marauder_mini.h CustomTFT_eSPI/
          cp /home/runner/work/ESP32Marauder/ESP32Marauder/User_Setup_og_marauder.h CustomTFT_eSPI/
          cp /home/runner/work/ESP32Marauder/ESP32Marauder/User_Setup_marauder_m5stickc.h CustomTFT_eSPI/
          cp /home/runner/work/ESP32Marauder/ESP32Marauder/User_Setup_marauder_m5stickcp2.h CustomTFT_eSPI/
          cp /home/runner/work/ESP32Marauder/ESP32Marauder/User_Setup_marauder_rev_feather.h CustomTFT_eSPI/
          pwd
          ls -la
          ls -la CustomTFT_eSPI
          
      #- name: Replace SD lib
      #  run: |
      #    rm -rf /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    cp -R /home/runner/work/ESP32Marauder/ESP32Marauder/2.0.4arduino-esp32/libraries/SD /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD
      #    ls -la /home/runner/.arduino15/packages/esp32/hardware/esp32/2.0.10/libraries/SD

      - name: Upload partitions
        run: |
          echo "CMD:find - finds any partitions directories first"
          find /home/runner/ -name "*TFT_eSPI*" 
          echo "CMD:find - finds any boards.txt files"
          find /home/runner/ -name "*boards.txt*" 
          echo "CMD:find - find existing min_spiffs used"
          find /home/runner/ -name "*min_spiffs*" 

      - name: Modify platform.txt
        run: |
          for i in $(find /home/runner/.arduino15/packages/esp32/tools/esp32-arduino-libs -name "ld_flags"); do
            sed -i 's/-mlongcalls /-mlongcalls -zmuldefs /' "$i"
          done
      
      # goodfellasthai: had to change the sed from the plus to User_Setup_og_marauder.h as that is first in user select
      - name: Configure TFT_eSPI and configs.h for Marauder M5StickC Plus 2
        run: |
          echo "CMD:pwd"
          pwd
          echo "CMD:ls"
          ls
          echo "CMD:find"
          find /home/runner/ -name "*TFT_eSPI*" 
          echo "CMD:cat /home/runner/work/ESP32Marauder/ESP32Marauder/CustomTFT_eSPI/User_Setup_Select.h"
          echo "First run should use this before /home/runner/Arduino/libraries/CustomTFT_eSPI created after first build"
          echo "That is why the sed always looks for the last executed build but here we just need to change original"
          cat /home/runner/work/ESP32Marauder/ESP32Marauder/CustomTFT_eSPI/User_Setup_Select.h
          #sed -i 's/^#include <User_Setup_og_marauder.h>/\/\/#include <User_Setup_og_marauder.h>/' /home/runner/Arduino/libraries/CustomTFT_eSPI/User_Setup_Select.h
          #sed -i 's/^\/\/#include <User_Setup_marauder_m5stickcp2.h>/#include <User_Setup_marauder_m5stickcp2.h>/' /home/runner/Arduino/libraries/CustomTFT_eSPI/User_Setup_Select.h
          sed -i 's/^#include <User_Setup_og_marauder.h>/\/\/#include <User_Setup_og_marauder.h>/' /home/runner/work/ESP32Marauder/ESP32Marauder/CustomTFT_eSPI/User_Setup_Select.h
          sed -i 's/^\/\/#include <User_Setup_marauder_m5stickcp2.h>/#include <User_Setup_marauder_m5stickcp2.h>/' /home/runner/work/ESP32Marauder/ESP32Marauder/CustomTFT_eSPI/User_Setup_Select.h
          sed -i 's/^  #define MARAUDER_REV_FEATHER/  \/\/#define MARAUDER_REV_FEATHER/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_MINI/  \/\/#define MARAUDER_MINI/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_V4/  \/\/#define MARAUDER_V4/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_V6/  \/\/#define MARAUDER_V6/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_V6_1/  \/\/#define MARAUDER_V6_1/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_KIT/  \/\/#define MARAUDER_KIT/' esp32_marauder/configs.h
          sed -i 's/^  #define GENERIC_ESP32/  \/\/#define GENERIC_ESP32/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_FLIPPER/  \/\/#define MARAUDER_FLIPPER/' esp32_marauder/configs.h
          sed -i 's/^  #define ESP32_LDDB/  \/\/#define ESP32_LDDB/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_DEV_BOARD_PRO/  \/\/#define MARAUDER_DEV_BOARD_PRO/' esp32_marauder/configs.h
          sed -i 's/^  #define MARAUDER_M5STICKC/  \/\/#define MARAUDER_M5STICKC/' esp32_marauder/configs.h
          sed -i 's/^  \/\/#define MARAUDER_M5STICKCP2/  #define MARAUDER_M5STICKCP2/' esp32_marauder/configs.h
          
      - name: Build Marauder for Marauder M5StickC Plus 2
        uses: ArminJo/arduino-test-compile@v3.2.1
        with:
          sketch-names: esp32_marauder.ino
          #required-libraries: |
          # ./CustomAsyncTCP
          # ./CustomMicroNMEA
          # ./CustomESPAsyncWebServer
          # ./CustomTFT_eSPI
          # ./Customlv_arduino
          # ./CustomJPEGDecoder
          # ./CustomNimBLE-Arduino
          # ./CustomAdafruit_NeoPixel
          # ./CustomArduinoJson
          # ./CustomLinkedList
          # ./CustomEspSoftwareSerial
          arduino-board-fqbn: esp32:esp32:m5stack_stickc_plus2:PartitionScheme=min_spiffs
          extra-arduino-cli-args: "--warnings none"
          
      - name: Rename Marauder M5StickC Plus 2 bin
        run: |
          mv ./esp32_marauder/build/esp32.esp32.m5stack_stickc_plus2/esp32_marauder.ino.bin ./esp32_marauder/build/esp32.esp32.m5stack_stickc_plus2/esp32_marauder.m5stickc_plus2.bin
          
      - name: Display finished bins
        run: |
          find ./esp32_marauder/build -name "*.bin"
          
      - name: 'Upload Marauder M5StickC Plus 2 Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: esp32_marauder.m5stickc_plus2.bin
          path: ./esp32_marauder/build/esp32.esp32.m5stack_stickc_plus2/esp32_marauder.m5stickc_plus2.bin
          retention-days: 5
                    
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false
        if: github.event_name != 'pull_request'
          
      - name: Upload Marauder M5StickC Plus 2 Asset
        id: upload-m5stickc-plus-2-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./esp32_marauder/build/esp32.esp32.m5stack_stickc_plus2/esp32_marauder.m5stickc_plus2.bin
          asset_name: esp32_marauder.m5stickc_plus2.bin
          asset_content_type: application/bin
        if: github.event_name != 'pull_request'        
